baseURL = "https://blog.watarona.me/"
title = "watarona tech blog"
googleAnalytics = "UA-123-456-789"
theme = "github-style"
copyright = "© 2019. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"

[params]
  author = "watarona"
  description = "watarona tech blog"
  github = "watarona"
  facebook = "example"
  twitter = "watarona"
  misskey = "user profile url"
  mastodon = "user profile url"
  email = "watarona0330@gmail.com"
  utterances = "example/example.github.io"
  avatar = "https://example.com/images/avatar.png"
  url = "https://blog.watarona.me"
  keywords = "blog, google analytics"

  [markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false